- name: Launch frontend
  community.docker.docker_container:
    name: front
    image: akpablin/tp-devops-front:latest
    networks:
      - name: my-network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python